---
- name: Create Pleiades download directory
  ansible.builtin.file:
    path: "{{ pleiades_download_dest | dirname }}"
    state: directory
    mode: "0755"
  when: pleiades_enabled

- name: Download Pleiades All in One DMG  # noqa: command-instead-of-module
  ansible.builtin.command: >
    curl
    --fail
    --location
    --output {{ pleiades_download_dest | quote }}
    {{ pleiades_url | quote }}
  args:
    creates: "{{ pleiades_download_dest }}"
  when:
    - pleiades_enabled
    - pleiades_url | length > 0
